In [1]:
import numpy as np

x = np.random.random()
print("Random number: {}".format(x))

Random number: 0.45034559405659835


In [2]:
print("Square root of {} is {}".format(x, np.sqrt(x)))

Square root of 0.45034559405659835 is 0.6710779344134319


In [3]:
print("x^sqrt(x) = {}".format(np.power(x, np.sqrt(x))))

x^sqrt(x) = 0.5854668509488271


In [4]:
matrix = np.random.random(3)
print("Random matrix {}".format(matrix))

Random matrix [0.37700016 0.68107512 0.56497113]


In [5]:
matrix = np.append(matrix, np.random.random(2))
print("New Matrix {}".format(matrix))

New Matrix [0.37700016 0.68107512 0.56497113 0.30234128 0.78433107]


In [6]:
print("Sine of matrix -> {}".format(np.sin(matrix)))

Sine of matrix -> [0.36813296 0.62962864 0.53539143 0.2977561  0.70635183]


In [7]:
# Tour of Numpy
mvalues = [0,1,5,6,80]
M = np.array(mvalues)
print("M = {}".format(M))

M = [ 0  1  5  6 80]


In [8]:
M

array([ 0,  1,  5,  6, 80])

In [9]:
mvalues

[0, 1, 5, 6, 80]

In [10]:
print(M * 39.3701) # Conversion to inches

[   0.       39.3701  196.8505  236.2206 3149.608 ]


In [11]:
print(M)

[ 0  1  5  6 80]


In [12]:
M * 39.3701

array([   0.    ,   39.3701,  196.8505,  236.2206, 3149.608 ])

In [14]:
x = np.arange(20, 104.75, 3.6)

In [15]:
x

array([ 20. ,  23.6,  27.2,  30.8,  34.4,  38. ,  41.6,  45.2,  48.8,
        52.4,  56. ,  59.6,  63.2,  66.8,  70.4,  74. ,  77.6,  81.2,
        84.8,  88.4,  92. ,  95.6,  99.2, 102.8])

In [16]:
x = np.linspace(20, 104.75, 10, endpoint=False)

In [17]:
x

array([20.   , 28.475, 36.95 , 45.425, 53.9  , 62.375, 70.85 , 79.325,
       87.8  , 96.275])

In [18]:
len(x)

10

In [19]:
_, spacing = np.linspace(20, 104.75, 10, retstep=True) # returns the spacing, _ is because we don't care about the actual array now

In [20]:
spacing

9.416666666666666

In [22]:
x = np.array([1,2,3,4])
print("x array: {}".format(x))
print("the type of x: {}".format(type(x)))
print("the dimension of x: {}".format(np.ndim(x)))

x array: [1 2 3 4]
the type of x: <class 'numpy.ndarray'>
the dimension of x: 1


In [23]:
# Tour of Numpy - Part 2
x = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]],
    [[9,10], [11,12]]
])
print("3D array {}".format(x))

3D array [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [24]:
print("number of dimensions: {}".format(x.ndim)) # number of dimensions

number of dimensions: 3


In [25]:
print("shape of the array: {}".format(np.shape(x)))

shape of the array: (3, 2, 2)


In [27]:
print("Sliced array: {}".format(x[1][1][0]))

Sliced array: 7


In [28]:
x = np.arange(24).reshape(4, 6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [30]:
print("Take every third item from every second row, [::2, ::3]\n{}".format(x[::2, ::3]))

Take every third item from every second row, [::2, ::3]
[[ 0  3]
 [12 15]]


In [31]:
# Zero array
Z = np.zeros((3, 5))
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
# Identity
I = np.identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
# k defines position of diagonal. if k = 0, we get ones on [0][0], [1][1] etc... with k = 1, we get them on [0][1], [1][2]...
# So we get elements equal to 1 on [i][i+k] where i is row index, and all the other elements are set to 0
np.eye(5, 8, k=1, dtype=int)

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0]])

In [35]:
np.eye(5, 8, k=0, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0]])

In [37]:
# More work on Matrices
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [38]:
b = np.ones((1, 2))
b

array([[1., 1.]])

In [40]:
# Creating a constant array
# c = np.full((2, 2), 7)
c = np.full((2, 2), 7, np.double)
c

array([[7., 7.],
       [7., 7.]])

In [41]:
# Identity matrix
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])