In [1]:
import numpy as np

x = np.random.random()
print("Random number: {}".format(x))

Random number: 0.8881248768588526


In [2]:
print("Square root of {} is {}".format(x, np.sqrt(x)))

Square root of 0.8881248768588526 is 0.9424037759150016


In [3]:
print("x^sqrt(x) = {}".format(np.power(x, np.sqrt(x))))

x^sqrt(x) = 0.8942145581728105


In [4]:
matrix = np.random.random(3)
print("Random matrix {}".format(matrix))

Random matrix [0.2692918  0.41214061 0.38360958]


In [5]:
matrix = np.append(matrix, np.random.random(2))
print("New Matrix {}".format(matrix))

New Matrix [0.2692918  0.41214061 0.38360958 0.65121801 0.9791294 ]


In [6]:
print("Sine of matrix -> {}".format(np.sin(matrix)))

Sine of matrix -> [0.26604883 0.40057161 0.37427013 0.60615559 0.83001211]


In [7]:
# Tour of Numpy
mvalues = [0,1,5,6,80]
M = np.array(mvalues)
print("M = {}".format(M))

M = [ 0  1  5  6 80]


In [8]:
M

array([ 0,  1,  5,  6, 80])

In [9]:
mvalues

[0, 1, 5, 6, 80]

In [10]:
print(M * 39.3701) # Conversion to inches

[   0.       39.3701  196.8505  236.2206 3149.608 ]


In [11]:
print(M)

[ 0  1  5  6 80]


In [12]:
M * 39.3701

array([   0.    ,   39.3701,  196.8505,  236.2206, 3149.608 ])

In [13]:
x = np.arange(20, 104.75, 3.6)

In [14]:
x

array([ 20. ,  23.6,  27.2,  30.8,  34.4,  38. ,  41.6,  45.2,  48.8,
        52.4,  56. ,  59.6,  63.2,  66.8,  70.4,  74. ,  77.6,  81.2,
        84.8,  88.4,  92. ,  95.6,  99.2, 102.8])

In [15]:
x = np.linspace(20, 104.75, 10, endpoint=False)

In [16]:
x

array([20.   , 28.475, 36.95 , 45.425, 53.9  , 62.375, 70.85 , 79.325,
       87.8  , 96.275])

In [17]:
len(x)

10

In [18]:
_, spacing = np.linspace(20, 104.75, 10, retstep=True) # returns the spacing, _ is because we don't care about the actual array now

In [19]:
spacing

9.416666666666666

In [20]:
x = np.array([1,2,3,4])
print("x array: {}".format(x))
print("the type of x: {}".format(type(x)))
print("the dimension of x: {}".format(np.ndim(x)))

x array: [1 2 3 4]
the type of x: <class 'numpy.ndarray'>
the dimension of x: 1


In [21]:
# Tour of Numpy - Part 2
x = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]],
    [[9,10], [11,12]]
])
print("3D array {}".format(x))

3D array [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [22]:
print("number of dimensions: {}".format(x.ndim)) # number of dimensions

number of dimensions: 3


In [23]:
print("shape of the array: {}".format(np.shape(x)))

shape of the array: (3, 2, 2)


In [24]:
print("Sliced array: {}".format(x[1][1][0]))

Sliced array: 7


In [25]:
x = np.arange(24).reshape(4, 6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [26]:
print("Take every third item from every second row, [::2, ::3]\n{}".format(x[::2, ::3]))

Take every third item from every second row, [::2, ::3]
[[ 0  3]
 [12 15]]


In [27]:
# Zero array
Z = np.zeros((3, 5))
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
# Identity
I = np.identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
# k defines position of diagonal. if k = 0, we get ones on [0][0], [1][1] etc... with k = 1, we get them on [0][1], [1][2]...
# So we get elements equal to 1 on [i][i+k] where i is row index, and all the other elements are set to 0
np.eye(5, 8, k=1, dtype=int)

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0]])

In [30]:
np.eye(5, 8, k=0, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0]])

In [31]:
# More work on Matrices
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [32]:
b = np.ones((1, 2))
b

array([[1., 1.]])

In [33]:
# Creating a constant array
# c = np.full((2, 2), 7)
c = np.full((2, 2), 7, np.double)
c

array([[7., 7.],
       [7., 7.]])

In [34]:
# Identity matrix
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [35]:
# Random matrix
e = np.random.random((2, 2))
e

array([[0.31515722, 0.50936895],
       [0.16228826, 0.68981447]])

In [36]:
# let's do it by hand
f = np.array([[1, 2, 3, 4], [11, 22, 33, 44], [111, 222, 333, 444]])
f

array([[  1,   2,   3,   4],
       [ 11,  22,  33,  44],
       [111, 222, 333, 444]])

In [37]:
np.shape(f)

(3, 4)

In [38]:
# Standard deviation
#A = np.random.random((12,12))
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [39]:
print("Standard deviation per row: {}".format(np.std(A, axis=0)))

Standard deviation per row: [1. 1.]


In [40]:
print("Standard deviation per column: {}".format(np.std(A, axis=1)))

Standard deviation per column: [0.5 0.5]


In [41]:
# Eigen Values
from numpy import linalg
A = np.diag((1, 2, 3))
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [42]:
eigenvalues, _ = linalg.eig(A)
print("For matrix\n{}\nEigen Values\n{}".format(A, eigenvalues))

For matrix
[[1 0 0]
 [0 2 0]
 [0 0 3]]
Eigen Values
[1. 2. 3.]


In [43]:
# Another example
B = np.array([[1, -1], [1, 1]])
B

array([[ 1, -1],
       [ 1,  1]])

In [44]:
eigenvalues,_ = linalg.eig(B)
print("For matrix\n{}\nEigen Values\n{}".format(B, eigenvalues))

For matrix
[[ 1 -1]
 [ 1  1]]
Eigen Values
[1.+1.j 1.-1.j]


In [45]:
# Covariance
A = (np.arange(4) + 1).reshape(2, 2)
print("For matrix\n{}\nCovariance\n{}".format(A, np.cov(A)))

For matrix
[[1 2]
 [3 4]]
Covariance
[[0.5 0.5]
 [0.5 0.5]]


In [46]:
# Example of expression
def gauss(x, sigma):
    return np.exp(-x**2/(2*sigma**2))/(sigma*np.sqrt(2*np.pi))

G_matrix_1 = gauss(np.linspace(-5, 5, 10), 1)
G_matrix_1

array([1.48671951e-06, 2.07440309e-04, 8.42153448e-03, 9.94771388e-02,
       3.41892294e-01, 3.41892294e-01, 9.94771388e-02, 8.42153448e-03,
       2.07440309e-04, 1.48671951e-06])

In [47]:
G_matrix_2 = gauss(np.linspace(-5, 5, 10), 2)
G_matrix_2

array([0.00876415, 0.03012145, 0.07603269, 0.14095594, 0.19192205,
       0.19192205, 0.14095594, 0.07603269, 0.03012145, 0.00876415])

In [48]:
G_matrix = [[], []]
G_matrix[0] = G_matrix_1
G_matrix[1] = G_matrix_2
print("Covariance of two different Gauss functions:")
np.cov(G_matrix)

Covariance of two different Gauss functions:


array([[0.01919045, 0.00888522],
       [0.00888522, 0.00519187]])

In [49]:
# Project (Determinants)
A = (np.arange(4) + 1).reshape(2, 2)
A

array([[1, 2],
       [3, 4]])

In [50]:
# Determinant
np.linalg.det(A)

-2.0000000000000004

In [55]:
B = np.array([ [[1,2],[3,4]], [[1,2],[2,1]], [[1,3],[3,1]] ])
B

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [2, 1]],

       [[1, 3],
        [3, 1]]])

In [56]:
# Determinant of B
np.linalg.det(B)

array([-2., -3., -8.])

In [57]:
C = np.array([[2,7],[8,4]])
C

array([[2, 7],
       [8, 4]])

In [58]:
np.linalg.det(C)

-47.999999999999986

In [59]:
print("det(A*C): {}".format(np.linalg.det(np.dot(A,C))))

det(A*C): 95.99999999999999


In [60]:
print("det(A)*det(C): {}".format(np.linalg.det(A)*np.linalg.det(C)))

det(A)*det(C): 95.99999999999999
