In [1]:
import numpy as np

x = np.random.random()
print("Random number: {}".format(x))

Random number: 0.45034559405659835


In [2]:
print("Square root of {} is {}".format(x, np.sqrt(x)))

Square root of 0.45034559405659835 is 0.6710779344134319


In [3]:
print("x^sqrt(x) = {}".format(np.power(x, np.sqrt(x))))

x^sqrt(x) = 0.5854668509488271


In [4]:
matrix = np.random.random(3)
print("Random matrix {}".format(matrix))

Random matrix [0.37700016 0.68107512 0.56497113]


In [5]:
matrix = np.append(matrix, np.random.random(2))
print("New Matrix {}".format(matrix))

New Matrix [0.37700016 0.68107512 0.56497113 0.30234128 0.78433107]


In [6]:
print("Sine of matrix -> {}".format(np.sin(matrix)))

Sine of matrix -> [0.36813296 0.62962864 0.53539143 0.2977561  0.70635183]


In [7]:
# Tour of Numpy
mvalues = [0,1,5,6,80]
M = np.array(mvalues)
print("M = {}".format(M))

M = [ 0  1  5  6 80]


In [8]:
M

array([ 0,  1,  5,  6, 80])

In [9]:
mvalues

[0, 1, 5, 6, 80]

In [10]:
print(M * 39.3701) # Conversion to inches

[   0.       39.3701  196.8505  236.2206 3149.608 ]


In [11]:
print(M)

[ 0  1  5  6 80]


In [12]:
M * 39.3701

array([   0.    ,   39.3701,  196.8505,  236.2206, 3149.608 ])

In [14]:
x = np.arange(20, 104.75, 3.6)

In [15]:
x

array([ 20. ,  23.6,  27.2,  30.8,  34.4,  38. ,  41.6,  45.2,  48.8,
        52.4,  56. ,  59.6,  63.2,  66.8,  70.4,  74. ,  77.6,  81.2,
        84.8,  88.4,  92. ,  95.6,  99.2, 102.8])

In [16]:
x = np.linspace(20, 104.75, 10, endpoint=False)

In [17]:
x

array([20.   , 28.475, 36.95 , 45.425, 53.9  , 62.375, 70.85 , 79.325,
       87.8  , 96.275])

In [18]:
len(x)

10

In [19]:
_, spacing = np.linspace(20, 104.75, 10, retstep=True) # returns the spacing, _ is because we don't care about the actual array now

In [20]:
spacing

9.416666666666666

In [22]:
x = np.array([1,2,3,4])
print("x array: {}".format(x))
print("the type of x: {}".format(type(x)))
print("the dimension of x: {}".format(np.ndim(x)))

x array: [1 2 3 4]
the type of x: <class 'numpy.ndarray'>
the dimension of x: 1


In [23]:
# Tour of Numpy - Part 2
x = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]],
    [[9,10], [11,12]]
])
print("3D array {}".format(x))

3D array [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [24]:
print("number of dimensions: {}".format(x.ndim)) # number of dimensions

number of dimensions: 3


In [25]:
print("shape of the array: {}".format(np.shape(x)))

shape of the array: (3, 2, 2)


In [27]:
print("Sliced array: {}".format(x[1][1][0]))

Sliced array: 7


In [28]:
x = np.arange(24).reshape(4, 6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [30]:
print("Take every third item from every second row, [::2, ::3]\n{}".format(x[::2, ::3]))

Take every third item from every second row, [::2, ::3]
[[ 0  3]
 [12 15]]


In [31]:
# Zero array
Z = np.zeros((3, 5))
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
# Identity
I = np.identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
# k defines position of diagonal. if k = 0, we get ones on [0][0], [1][1] etc... with k = 1, we get them on [0][1], [1][2]...
# So we get elements equal to 1 on [i][i+k] where i is row index, and all the other elements are set to 0
np.eye(5, 8, k=1, dtype=int)

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0]])

In [35]:
np.eye(5, 8, k=0, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0]])

In [37]:
# More work on Matrices
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [38]:
b = np.ones((1, 2))
b

array([[1., 1.]])

In [40]:
# Creating a constant array
# c = np.full((2, 2), 7)
c = np.full((2, 2), 7, np.double)
c

array([[7., 7.],
       [7., 7.]])

In [41]:
# Identity matrix
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [42]:
# Random matrix
e = np.random.random((2, 2))
e

array([[0.57820511, 0.60663686],
       [0.28234751, 0.00578166]])

In [44]:
# let's do it by hand
f = np.array([[1, 2, 3, 4], [11, 22, 33, 44], [111, 222, 333, 444]])
f

array([[  1,   2,   3,   4],
       [ 11,  22,  33,  44],
       [111, 222, 333, 444]])

In [45]:
np.shape(f)

(3, 4)

In [49]:
# Standard deviation
A = np.random.random((12,12))
A

array([[0.62831233, 0.48676947, 0.31615826, 0.97624044, 0.27563509,
        0.08894831, 0.63112075, 0.92216499, 0.15927577, 0.02738089,
        0.07320255, 0.34904362],
       [0.34452585, 0.83720213, 0.47292909, 0.52808402, 0.82992404,
        0.66453583, 0.45263729, 0.56939214, 0.24606176, 0.06975375,
        0.08240646, 0.54342834],
       [0.78535397, 0.72332423, 0.17813296, 0.46934966, 0.80537273,
        0.26118456, 0.20004617, 0.25447969, 0.37352888, 0.01615559,
        0.15692987, 0.80209506],
       [0.68328029, 0.18958071, 0.16213572, 0.40860072, 0.91758647,
        0.62766645, 0.14580868, 0.4308944 , 0.40990703, 0.94069238,
        0.66798339, 0.55610267],
       [0.20454018, 0.2976387 , 0.23267599, 0.91875446, 0.95529967,
        0.6505987 , 0.71329758, 0.80978677, 0.94474739, 0.05806697,
        0.72837893, 0.998772  ],
       [0.91294651, 0.74992402, 0.80649974, 0.46918992, 0.57353426,
        0.39097725, 0.33645995, 0.54570965, 0.24329219, 0.01177858,
        0.21111739,

In [51]:
print("Standard deviation per row: {}".format(np.std(A, axis=0)))

Standard deviation per row: [0.26857635 0.27622283 0.32711881 0.23579646 0.3090928  0.25653954
 0.27131952 0.28954347 0.30494118 0.3288447  0.28262528 0.180626  ]


In [52]:
print("Standard deviation per column: {}".format(np.std(A, axis=1)))

Standard deviation per column: [0.30845247 0.24109111 0.27634086 0.25907137 0.32273422 0.25103536
 0.18095874 0.2771657  0.29586545 0.2848963  0.31986803 0.35049373]
